version: '3.8'

services:
  web:
    build: .
    working_dir: /app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload" ]
    ports:
      - "8000:80"
    networks:
      - backend_network
    depends_on:
      - postgres
    volumes:
      - .:/app